// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqpEVaaiwphEJisqBHxoiAA6Myim5oTkA',
    appId: '1:362440802072:android:01c97b0951f0d4651d286d',
    messagingSenderId: '362440802072',
    projectId: 'basketbuddb',
    databaseURL: 'https://basketbuddb-default-rtdb.firebaseio.com',
    storageBucket: 'basketbuddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIRDGkGmOl8CJwxB82BQySWeeA4WjNdV0',
    appId: '1:362440802072:ios:21fde71ca303e7731d286d',
    messagingSenderId: '362440802072',
    projectId: 'basketbuddb',
    databaseURL: 'https://basketbuddb-default-rtdb.firebaseio.com',
    storageBucket: 'basketbuddb.appspot.com',
    iosClientId:
        '362440802072-2tedsm46fdmvrsrkahrn2cu5ofrmn1dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.basketbudPrototype',
  );
}
